name: Build Project Matrixx for tapas (Clean Extraction)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget unzip python3

      - name: Download MIUI firmware
        run: |
          wget https://bn.d.miui.com/OS2.0.12.0.VMTMIXM/tapas_global_images_OS2.0.12.0.VMTMIXM_20250523.0000.00_15.0_global_c36b8ae07a.tgz -O firmware.tgz
          mkdir firmware && tar -xvzf firmware.tgz -C firmware

      - name: Clone Project Matrixx
        run: |
          git clone https://github.com/ProjectMatrixx/android matrixx
          cd matrixx
          chmod +x build.sh

      - name: Build ROM
        run: |
          cd matrixx
          ./build.sh tapas

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Matrixx-tapas-build
          path: matrixx/out
